services:
  - type: web
    name: travel-itinerary-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: travel-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true